<?php

return [
    'roles' => [
        'super-admin',
        'gm',
        'sales-manager',
        'sales',
        'finance',
        'operation',
        'head-pool',
        'pool-staff',
    ],

    'permissions' => [
        'dashboard.view',

        'clients.view',
        'clients.create',
        'clients.update',
        'clients.delete',
        'meeting-logs.view',
        'meeting-logs.create',
        'meeting-logs.update',
        'meeting-logs.delete',

        'vehicles.view',
        'vehicles.create',
        'vehicles.update',
        'vehicles.delete',
        'vehicles.update-status',

        'drivers.view',
        'drivers.create',
        'drivers.update',
        'drivers.delete',

        'pool.view-all',
        'pool.view-own',
        'pool.assign-driver',
        'pool.update-status',
        'pool.view-schedule',

        'bookings.view',
        'bookings.create',
        'bookings.update',
        'bookings.cancel',
        'bookings.approve',

        'purchase-orders.view',
        'purchase-orders.create',
        'purchase-orders.approve',
        'invoices.view',
        'invoices.create',
        'invoices.update',
        'payments.view',
        'payments.create',
        'evouchers.view',
        'evouchers.create',
        'evouchers.update',

        'maintenance.view',
        'maintenance.create',
        'maintenance.update',

        'reports.view',
        'reports.export',

        'hr.view',
        'hr.drivers.manage',
        'hr.attendance.manage',
        'hr.licenses.manage',

        'admin.access',
    ],

    'role_permissions' => [
        'super-admin' => ['*'],
        'gm' => [
            'dashboard.view',
            'reports.view',
            'reports.export',
            'clients.view',
            'vehicles.view',
            'drivers.view',
            'bookings.view',
            'invoices.view',
            'payments.view',
            'maintenance.view',
        ],
        'sales-manager' => [
            'dashboard.view',
            'clients.*',
            'meeting-logs.*',
            'bookings.*',
            'purchase-orders.view',
            'purchase-orders.approve',
        ],
        'sales' => [
            'dashboard.view',
            'clients.view',
            'clients.create',
            'clients.update',
            'meeting-logs.*',
            'bookings.view',
            'bookings.create',
            'bookings.update',
        ],
        'finance' => [
            'dashboard.view',
            'purchase-orders.*',
            'invoices.*',
            'payments.*',
            'evouchers.*',
        ],
        'operation' => [
            'dashboard.view',
            'vehicles.*',
            'drivers.view',
            'maintenance.*',
        ],
        'head-pool' => [
            'dashboard.view',
            'pool.view-all',
            'pool.assign-driver',
            'pool.update-status',
            'pool.view-schedule',
            'vehicles.view',
            'drivers.view',
            'bookings.view',
        ],
        'pool-staff' => [
            'dashboard.view',
            'pool.view-own',
            'pool.assign-driver',
            'pool.update-status',
            'pool.view-schedule',
            'vehicles.view',
            'drivers.view',
            'bookings.view',
        ],
    ],

    'demo_users' => [
        ['name' => 'Super Admin', 'email' => 'superadmin@blueerp.test', 'role' => 'super-admin'],
        ['name' => 'GM User', 'email' => 'gm@blueerp.test', 'role' => 'gm'],
        ['name' => 'Sales Manager User', 'email' => 'salesmanager@blueerp.test', 'role' => 'sales-manager'],
        ['name' => 'Sales User', 'email' => 'sales@blueerp.test', 'role' => 'sales'],
        ['name' => 'Finance User', 'email' => 'finance@blueerp.test', 'role' => 'finance'],
        ['name' => 'Operation User', 'email' => 'operation@blueerp.test', 'role' => 'operation'],
        ['name' => 'Head Pool User', 'email' => 'headpool@blueerp.test', 'role' => 'head-pool'],
        ['name' => 'Pool Staff User', 'email' => 'poolstaff@blueerp.test', 'role' => 'pool-staff'],
    ],
];
